name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs-version: ['27.2', '28.2', '29.1']

    steps:
      - uses: actions/checkout@v3

      - name: Set up Emacs ${{ matrix.emacs-version }}
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}

      - name: Install dependencies
        run: |
          emacs --version
          # Install package dependencies (this would typically be done via doom sync)
          # For CI, we'll verify syntax only

      - name: Check syntax
        run: make check-syntax

      - name: Byte-compile
        run: make compile

      # TODO: Enable when tests are implemented
      # - name: Run tests
      #   run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: '29.1'

      - name: Lint
        run: make lint
